// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel ParticleMain

struct Particle
{
    float3 basePosition;
    float3 position;
    float4 color;
    float scale;
};

RWStructuredBuffer<Particle> _ParticleBuffer;
float _DeltaTime;
int _ParticleCount;

[numthreads(64,1,1)]
void ParticleMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)_ParticleCount) return;

    Particle p = _ParticleBuffer[id.x];
    p.position += (p.basePosition - p.position) * _DeltaTime;
    _ParticleBuffer[id.x] = p;
}
