// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float> Result;
Texture2D<float4> Texture;

int Length;
int pixelPerDivW;
int pixelPerDivH;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float result = 0;
    uint halfWidthPixelPerDiv = (uint)pixelPerDivW / 2u;
    uint halfHeightPixelPerDiv = (uint)pixelPerDivH / 2u;

    for (int i = -(int)halfHeightPixelPerDiv; i <= (int)halfHeightPixelPerDiv; i++)
    {
        for (int j = -(int)halfWidthPixelPerDiv; j <= (int)halfWidthPixelPerDiv; j++)
        {
            uint u = (id.x * pixelPerDivW) + halfWidthPixelPerDiv + j;
            uint v = (id.y * pixelPerDivH) + halfHeightPixelPerDiv + i;
            float4 tex = Texture[uint2(u, v)];
            result += tex.a;
        }
    }
    
    float denom = 1. / (pixelPerDivW * pixelPerDivH);
    int index = id.y * Length + id.x;
    
    Result[index] = result * denom;
}
